services:
  - type: web
    name: noble-59min
    env: node
    plan: free
    buildCommand: |
      bash render-build.sh
      npm install
    startCommand: node index.js
    envVars:
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
